-- Appliance Opportunity Marketplace foundation
-- Run only after review in Supabase SQL Editor.

create table if not exists public.marketplace_buyers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'pending',
  full_name text,
  business_name text,
  email text,
  phone text,
  business_type text,
  home_city text,
  home_state text,
  service_radius_miles integer,
  service_areas jsonb not null default '[]'::jsonb,
  appliance_preferences jsonb not null default '[]'::jsonb,
  condition_preferences jsonb not null default '[]'::jsonb,
  commercial_interest boolean not null default false,
  max_opportunity_price numeric(10,2),
  reliability_score numeric(5,2) not null default 100,
  total_claims integer not null default 0,
  completed_pickups integer not null default 0,
  cancellations integer not null default 0,
  no_shows integer not null default 0,
  average_contact_minutes numeric(10,2),
  plan_type text not null default 'pay_per_opportunity',
  verified boolean not null default false
);

create table if not exists public.marketplace_territories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  state text not null,
  city text,
  county text,
  zip_codes jsonb not null default '[]'::jsonb,
  territory_status text not null default 'open',
  coverage_level text not null default 'none',
  protected_buyer_id bigint references public.marketplace_buyers(id),
  opportunity_window_minutes integer not null default 30,
  notes text
);

create table if not exists public.marketplace_opportunities (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  source_request_id text,
  territory_id bigint references public.marketplace_territories(id),
  city text,
  state text,
  zip_code text,
  approximate_area text,
  residential_or_commercial text not null default 'residential',
  appliance_count integer not null default 1,
  appliances jsonb not null default '[]'::jsonb,
  photo_urls jsonb not null default '[]'::jsonb,
  photo_count integer not null default 0,
  visual_quality_score numeric(5,2),
  completeness_score numeric(5,2),
  demand_score numeric(5,2),
  opportunity_class text,
  hot_opportunity boolean not null default false,
  owner_reported_summary text,
  access_summary text,
  urgency text,
  opportunity_price numeric(10,2),
  customer_name text,
  customer_phone text,
  customer_email text,
  exact_address text,
  customer_private_locked boolean not null default true,
  accepted_at timestamptz,
  purchased_at timestamptz,
  purchased_by bigint references public.marketplace_buyers(id),
  contacted_at timestamptz,
  pickup_completed_at timestamptz,
  expires_at timestamptz
);

create table if not exists public.marketplace_offers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  opportunity_id bigint not null references public.marketplace_opportunities(id) on delete cascade,
  buyer_id bigint not null references public.marketplace_buyers(id) on delete cascade,
  offered_at timestamptz not null default now(),
  expires_at timestamptz,
  status text not null default 'offered',
  viewed_at timestamptz,
  claimed_at timestamptz,
  passed_at timestamptz,
  payment_status text not null default 'unpaid'
);

create table if not exists public.marketplace_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  opportunity_id bigint references public.marketplace_opportunities(id) on delete cascade,
  buyer_id bigint references public.marketplace_buyers(id) on delete set null,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb
);

create index if not exists idx_marketplace_opportunities_status on public.marketplace_opportunities(status);
create index if not exists idx_marketplace_opportunities_location on public.marketplace_opportunities(state, city, zip_code);
create index if not exists idx_marketplace_offers_buyer_status on public.marketplace_offers(buyer_id, status);
create index if not exists idx_marketplace_territories_location on public.marketplace_territories(state, city);

alter table public.marketplace_buyers enable row level security;
alter table public.marketplace_territories enable row level security;
alter table public.marketplace_opportunities enable row level security;
alter table public.marketplace_offers enable row level security;
alter table public.marketplace_events enable row level security;

-- No public policies are added intentionally.
-- Private customer fields must remain server-side until payment/assignment logic explicitly unlocks access.
