-- Applied to Supabase project: free-reliable-appliance-pickup-partners
-- 2026-09-30
-- Purpose: connect future lead submissions to source/page attribution and
-- create a secure internal table for daily search-performance measurements.

alter table public.appliance_leads
  add column if not exists source_channel text,
  add column if not exists landing_page text,
  add column if not exists referrer_url text,
  add column if not exists utm_source text,
  add column if not exists utm_medium text,
  add column if not exists utm_campaign text,
  add column if not exists utm_term text,
  add column if not exists utm_content text,
  add column if not exists gclid text,
  add column if not exists msclkid text,
  add column if not exists fbclid text,
  add column if not exists session_id text,
  add column if not exists tracking_data jsonb not null default '{}'::jsonb;

create index if not exists idx_appliance_leads_created_at
  on public.appliance_leads (created_at desc);
create index if not exists idx_appliance_leads_source_page_created
  on public.appliance_leads (source_page, created_at desc);
create index if not exists idx_appliance_leads_source_channel_created
  on public.appliance_leads (source_channel, created_at desc);

create policy "clients_cannot_access_appliance_leads"
on public.appliance_leads
for all
to anon, authenticated
using (false)
with check (false);

create table if not exists public.lead_events (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.appliance_leads(id),
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.lead_events enable row level security;

create policy "clients_cannot_access_lead_events"
on public.lead_events
for all
to anon, authenticated
using (false)
with check (false);

create index if not exists idx_lead_events_lead_created
  on public.lead_events (lead_id, created_at desc);

create table if not exists public.seo_daily_metrics (
  id bigint generated by default as identity primary key,
  metric_date date not null,
  source_system text not null,
  search_engine text not null,
  query text not null default '',
  page_url text not null default '',
  country text not null default '',
  device text not null default '',
  clicks integer not null default 0 check (clicks >= 0),
  impressions integer not null default 0 check (impressions >= 0),
  ctr numeric not null default 0 check (ctr >= 0 and ctr <= 1),
  avg_position numeric,
  imported_at timestamptz not null default now(),
  constraint seo_daily_metrics_search_engine_check
    check (search_engine in ('google','bing','other'))
);

alter table public.seo_daily_metrics enable row level security;

create policy "clients_cannot_access_seo_daily_metrics"
on public.seo_daily_metrics
for all
to anon, authenticated
using (false)
with check (false);

create unique index if not exists uq_seo_daily_metrics_dimensions
  on public.seo_daily_metrics
  (metric_date, source_system, search_engine, query, page_url, country, device);

create index if not exists idx_seo_daily_metrics_page_date
  on public.seo_daily_metrics (page_url, metric_date desc);
create index if not exists idx_seo_daily_metrics_query_date
  on public.seo_daily_metrics (query, metric_date desc);
