-- Applied to Supabase project: free-reliable-appliance-pickup-partners
-- 2026-09-30
-- Stores finalized Search Console period snapshots and exposes an internal
-- page-level funnel report for ranking -> clicks -> leads.

create table if not exists public.seo_period_metrics (
  id bigint generated by default as identity primary key,
  period_start date not null,
  period_end date not null,
  source_system text not null,
  search_engine text not null,
  metric_scope text not null,
  query text not null default '',
  page_url text not null default '',
  country text not null default '',
  clicks integer not null default 0 check (clicks >= 0),
  impressions integer not null default 0 check (impressions >= 0),
  ctr numeric not null default 0 check (ctr >= 0 and ctr <= 1),
  avg_position numeric,
  captured_at timestamptz not null default now(),
  constraint seo_period_metrics_engine_check
    check (search_engine in ('google','bing','other')),
  constraint seo_period_metrics_scope_check
    check (metric_scope in ('site','query','page','query_page'))
);

alter table public.seo_period_metrics enable row level security;

create policy "clients_cannot_access_seo_period_metrics"
on public.seo_period_metrics
for all
to anon, authenticated
using (false)
with check (false);

create unique index if not exists uq_seo_period_metrics_dimensions
  on public.seo_period_metrics
  (period_start, period_end, source_system, search_engine, metric_scope, query, page_url, country);

create index if not exists idx_seo_period_metrics_page_period
  on public.seo_period_metrics (page_url, period_end desc);

create index if not exists idx_seo_period_metrics_query_period
  on public.seo_period_metrics (query, period_end desc);

create or replace view public.reporting_page_funnel
with (security_invoker = true)
as
with latest_period as (
  select max(period_end) as period_end
  from public.seo_period_metrics
  where search_engine='google'
),
period_bounds as (
  select max(period_start) as period_start, max(period_end) as period_end
  from public.seo_period_metrics
  where search_engine='google'
    and period_end=(select period_end from latest_period)
),
seo as (
  select
    page_url,
    sum(clicks) as clicks,
    sum(impressions) as impressions,
    case when sum(impressions)>0 then sum(clicks)::numeric/sum(impressions) else 0 end as ctr,
    case when sum(impressions)>0 then sum(avg_position*impressions)/sum(impressions) else null end as avg_position
  from public.seo_period_metrics
  where metric_scope='page'
    and search_engine='google'
    and period_end=(select period_end from latest_period)
  group by page_url
),
leads as (
  select
    coalesce(source_page, landing_page) as page_url,
    count(*) as leads,
    count(*) filter (where status not in ('new','pending')) as progressed_leads
  from public.appliance_leads
  where created_at::date between
    (select period_start from period_bounds)
    and (select period_end from period_bounds)
  group by coalesce(source_page, landing_page)
)
select
  coalesce(seo.page_url, leads.page_url) as page_url,
  (select period_start from period_bounds) as period_start,
  (select period_end from period_bounds) as period_end,
  coalesce(seo.clicks,0)::integer as organic_clicks,
  coalesce(seo.impressions,0)::integer as organic_impressions,
  coalesce(seo.ctr,0) as organic_ctr,
  seo.avg_position,
  coalesce(leads.leads,0)::integer as leads,
  coalesce(leads.progressed_leads,0)::integer as progressed_leads,
  case
    when coalesce(seo.clicks,0)>0
    then coalesce(leads.leads,0)::numeric/seo.clicks
    else null
  end as lead_per_click
from seo
full outer join leads using (page_url);

revoke all on public.reporting_page_funnel from anon, authenticated;
grant select on public.reporting_page_funnel to service_role;
